# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equations_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class UIElementHelpWindow(QtWidgets.QWidget):
    def setupUi(self):
        self.setObjectName("Submuestreo de elementos")
        self.setObjectName("EquationDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("UIElementHelpWindow", "Submuestreo de elementos"))
        self.groupBox.setTitle(_translate("UIElementHelpWindow", "Instrucciones"))
        self.label.setText(_translate("UIElementHelpWindow", "* Ingrese la lista en formato: a,b,c,..."))
        self.label_2.setText(_translate("UIElementHelpWindow", "* Las columnas empiezan desde el índice cero (0)"))
        self.label_3.setText(_translate("UIElementHelpWindow", "* Para números por comas sin espacios"))
        self.label_4.setText(_translate("UIElementHelpWindow", "* Ingresar solamente números enteros"))
        self.label_5.setText(_translate("UIElementHelpWindow", "* Ingresar un mínimo de 7 números"))

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    UIEquationWindow = QtWidgets.QWidget()
    ui = UIElementHelpWindow()
    ui.setupUi(UIElementHelpWindow, "example")
    UIElementHelpWindow.show()
    sys.exit(app.exec_())
