# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equations_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UIEquationWindow(object):
    def setupUi(self, UIEquationWindow, case):
        UIEquationWindow.setObjectName("Algoritmo")
        UIEquationWindow.resize(520, 234)
        self.equationGroupBox = QtWidgets.QGroupBox(UIEquationWindow)
        self.equationGroupBox.setGeometry(QtCore.QRect(10, 10, 501, 211))
        self.equationGroupBox.setObjectName("equationGroupBox")
        self.scrollArea = QtWidgets.QScrollArea(self.equationGroupBox)
        self.scrollArea.setGeometry(QtCore.QRect(0, 20, 501, 191))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.equation = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.equation.setGeometry(QtCore.QRect(10, 10, 471, 171))
        self.equation.setText("")
        # self.equation.setPixmap(QtGui.QPixmap("assets/equations/fista.png"))
        self.update_equation(case)
        self.equation.setScaledContents(True)
        self.equation.setObjectName("equation")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(UIEquationWindow, case)
        QtCore.QMetaObject.connectSlotsByName(UIEquationWindow)

    def retranslateUi(self, UIEquationWindow, case):
        _translate = QtCore.QCoreApplication.translate
        UIEquationWindow.setWindowTitle(_translate("UIEquationWindow", f"Algoritmo {case}"))
        self.equationGroupBox.setTitle(_translate("UIEquationWindow", "Algoritmo y parámetros"))

    def update_equation(self, case):
        if case == 'FISTA':
            self.equation.setPixmap(QtGui.QPixmap("assets/equations/fista.png"))
        else:
            self.equation.setPixmap(QtGui.QPixmap("assets/equations/fista.png"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    UIEquationWindow = QtWidgets.QWidget()
    ui = UIEquationWindow()
    ui.setupUi(UIEquationWindow, "example")
    UIEquationWindow.show()
    sys.exit(app.exec_())
