# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equations_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class UIJitterWindow(QtWidgets.QWidget):
    def setupUi(self):
        self.setObjectName("Algoritmo")
        self.setObjectName("JitterDialog")
        self.setWindowIcon(QIcon("Desarrollo/ReDS/assets/icons/g868.ico"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.equationGroupBox = QtWidgets.QGroupBox(self)
        self.equationGroupBox.setObjectName("equationGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.equationGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.equation = QtWidgets.QLabel(self.equationGroupBox)
        self.equation.setText("")
        self.equation.setPixmap(QtGui.QPixmap("Desarrollo/ReDS/assets/equations/jitter.png"))
        self.equation.setScaledContents(False)
        self.equation.setObjectName("jitter")
        self.horizontalLayout_2.addWidget(self.equation)
        self.horizontalLayout.addWidget(self.equationGroupBox)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("UIEquationWindow", "Submuestreo de tipo jitter"))
        self.equationGroupBox.setTitle(_translate("UIEquationWindow", ""))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    UIEquationWindow = QtWidgets.QWidget()
    ui = UIJitterWindow()
    ui.setupUi(UIJitterWindow)
    UIJitterWindow.show()
    sys.exit(app.exec_())
