# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ultimate_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from Desarrollo.ReDS.mainA_window import UIMainAWindow
from Desarrollo.ReDS.mainB_window import UIMainBWindow


def solve_path(relative_path):
    if hasattr(sys, '_MEIPASS'):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath('.'), relative_path)


class UILauncherWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(UILauncherWindow, self).__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("launcherWindow")
        self.resize(975, 380)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upperLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.upperLogoLabel.setText("")
        self.upperLogoLabel.setPixmap(QtGui.QPixmap(solve_path("assets/logos/upper_logo.png")))
        self.upperLogoLabel.setObjectName("upperLogoLabel")
        self.verticalLayout.addWidget(self.upperLogoLabel)
        self.moduleHLayout = QtWidgets.QHBoxLayout()
        self.moduleHLayout.setObjectName("moduleHLayout")
        self.moduleAPushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moduleAPushButton.setFont(font)
        self.moduleAPushButton.setObjectName("moduleAPushButton")
        self.moduleHLayout.addWidget(self.moduleAPushButton)
        self.moduleBPushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moduleBPushButton.setFont(font)
        self.moduleBPushButton.setObjectName("moduleBPushButton")
        self.moduleHLayout.addWidget(self.moduleBPushButton)
        self.verticalLayout.addLayout(self.moduleHLayout)
        self.lowerLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.lowerLogoLabel.setText("")
        self.lowerLogoLabel.setPixmap(QtGui.QPixmap(solve_path("assets/logos/lower_logo.png")))
        self.lowerLogoLabel.setObjectName("lowerLogoLabel")
        self.verticalLayout.addWidget(self.lowerLogoLabel)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        # actions

        self.moduleAPushButton.clicked.connect(self.open_module_A)
        self.moduleBPushButton.clicked.connect(self.open_module_B)

    def open_module_A(self):
        self.main_A_window = QtWidgets.QWidget()
        self.ui_main_A_window = UIMainAWindow(self)
        self.ui_main_A_window.show()
        self.hide()

    def open_module_B(self):
        self.main_B_window = QtWidgets.QWidget()
        self.ui_main_B_window = UIMainBWindow(self)
        self.ui_main_B_window.show()
        self.hide()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("launcherWindow", "ReDs - Universidad Industrial de Santander"))
        self.moduleAPushButton.setText(_translate("launcherWindow", "Modulo A: Reconstrucción de trazas"))
        self.moduleBPushButton.setText(_translate("launcherWindow", "Modulo B: Reconstrucción de disparos"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    LauncherWindow = UILauncherWindow()

    qtRectangle = LauncherWindow.frameGeometry()
    centerPoint = QtWidgets.QDesktopWidget().availableGeometry().center()
    qtRectangle.moveCenter(centerPoint)
    LauncherWindow.move(qtRectangle.topLeft())
    enterPoint = QtWidgets.QDesktopWidget().availableGeometry().center()
    qtRectangle.moveCenter(centerPoint)
    LauncherWindow.move(qtRectangle.topLeft())

    LauncherWindow.show()
    sys.exit(app.exec_())
