# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ultimate_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from Desarrollo.ReDS.mainA_window import UIMainAWindow
from Desarrollo.ReDS.mainB_window import UIMainBWindow


def solve_path(relative_path):
    if hasattr(sys, '_MEIPASS'):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath('.'), relative_path)


class UILauncherWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(UILauncherWindow, self).__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("launcherWindow")
        self.resize(975, 603)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/g868.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upperLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.upperLogoLabel.setEnabled(True)
        self.upperLogoLabel.setText("")
        self.upperLogoLabel.setPixmap(QtGui.QPixmap("assets/logos/upper_logoa.png"))
        self.upperLogoLabel.setScaledContents(False)
        self.upperLogoLabel.setObjectName("upperLogoLabel")
        self.verticalLayout.addWidget(self.upperLogoLabel)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("assets/logos/logo.png"))
        self.logoLabel.setScaledContents(False)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout.addWidget(self.logoLabel)
        self.text1Label = QtWidgets.QLabel(self.centralwidget)
        self.text1Label.setTextFormat(QtCore.Qt.RichText)
        self.text1Label.setObjectName("text1Label")
        self.verticalLayout.addWidget(self.text1Label)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.moduleHLayout = QtWidgets.QHBoxLayout()
        self.moduleHLayout.setObjectName("moduleHLayout")
        self.moduleAPushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moduleAPushButton.sizePolicy().hasHeightForWidth())
        self.moduleAPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moduleAPushButton.setFont(font)
        self.moduleAPushButton.setObjectName("moduleAPushButton")
        self.moduleHLayout.addWidget(self.moduleAPushButton)
        self.moduleBPushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moduleBPushButton.setFont(font)
        self.moduleBPushButton.setObjectName("moduleBPushButton")
        self.moduleHLayout.addWidget(self.moduleBPushButton)
        self.verticalLayout.addLayout(self.moduleHLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.lowerLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.lowerLogoLabel.setText("")
        self.lowerLogoLabel.setPixmap(QtGui.QPixmap("assets/logos/lower_logoa.png"))
        self.lowerLogoLabel.setObjectName("lowerLogoLabel")
        self.verticalLayout.addWidget(self.lowerLogoLabel)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        # actions

        self.moduleAPushButton.clicked.connect(self.open_module_A)
        self.moduleBPushButton.clicked.connect(self.open_module_B)

    def open_module_A(self):
        self.main_A_window = QtWidgets.QWidget()
        self.ui_main_A_window = UIMainAWindow(self)
        self.ui_main_A_window.show()
        self.hide()

    def open_module_B(self):
        self.main_B_window = QtWidgets.QWidget()
        self.ui_main_B_window = UIMainBWindow(self)
        self.ui_main_B_window.show()
        self.hide()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("launcherWindow", "ReDs - Universidad Industrial de Santander"))
        self.text1Label.setText(_translate("MainWindow",
                                           "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Reconstrucción de Datos Sísmicos - ReDS</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">ReDS - RG</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Reconstrucción de Receptores</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">ReDS - SG</span></p><p align=\"center\"><span style=\" font-size:12pt;\">Reconstrucción de Disparos</span></p></body></html>"))
        self.moduleAPushButton.setText(_translate("MainWindow", "Iniciar RG"))
        self.moduleBPushButton.setText(_translate("MainWindow", "Iniciar SG"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    LauncherWindow = UILauncherWindow()

    qtRectangle = LauncherWindow.frameGeometry()
    centerPoint = QtWidgets.QDesktopWidget().availableGeometry().center()
    qtRectangle.moveCenter(centerPoint)
    LauncherWindow.move(qtRectangle.topLeft())
    enterPoint = QtWidgets.QDesktopWidget().availableGeometry().center()
    qtRectangle.moveCenter(centerPoint)
    LauncherWindow.move(qtRectangle.topLeft())

    LauncherWindow.show()
    sys.exit(app.exec_())
