# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equations_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class UISeedHelpWindow(QtWidgets.QWidget):
    def setupUi(self):
        self.setObjectName("Uso de semilla")
        self.setObjectName("EquationDialog")
        self.resize(250, 100)
        self.setWindowIcon(QIcon('assets/icons/g868.ico'))
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("UISeedHelpWindow", "Uso de semilla"))
        self.groupBox.setTitle(_translate("UISeedHelpWindow", "Instrucciones"))
        self.label.setText(_translate("UISeedHelpWindow", "El uso de la semilla fija los parámetros de"))
        self.label_2.setText(_translate("UISeedHelpWindow", "submuestreo aleatorio y jitter mediante"))
        self.label_3.setText(_translate("UISeedHelpWindow", "el valor establecido que se repetirá"))
        self.label_4.setText(_translate("UISeedHelpWindow", "cada vez que se ejecute el mismo"))
        self.label_5.setText(_translate("UISeedHelpWindow", " experimento"))

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    UIEquationWindow = QtWidgets.QWidget()
    ui = UISeedHelpWindow()
    ui.setupUi(UISeedHelpWindow, "example")
    UISeedHelpWindow.show()
    sys.exit(app.exec_())
