# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equations_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EquationDialog(object):
    def setupUi(self, EquationDialog):
        EquationDialog.setObjectName("EquationDialog")
        EquationDialog.resize(520, 234)
        self.equationGroupBox = QtWidgets.QGroupBox(EquationDialog)
        self.equationGroupBox.setGeometry(QtCore.QRect(10, 10, 501, 211))
        self.equationGroupBox.setObjectName("equationGroupBox")
        self.scrollArea = QtWidgets.QScrollArea(self.equationGroupBox)
        self.scrollArea.setGeometry(QtCore.QRect(0, 20, 501, 191))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 189))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.equation = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.equation.setGeometry(QtCore.QRect(10, 10, 471, 171))
        self.equation.setText("")
        self.equation.setPixmap(QtGui.QPixmap("../assets/equations/fista.png"))
        self.equation.setScaledContents(True)
        self.equation.setObjectName("equation")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(EquationDialog)
        QtCore.QMetaObject.connectSlotsByName(EquationDialog)

    def retranslateUi(self, EquationDialog):
        _translate = QtCore.QCoreApplication.translate
        EquationDialog.setWindowTitle(_translate("EquationDialog", "Dialog"))
        self.equationGroupBox.setTitle(_translate("EquationDialog", "Algoritmo y parámetros"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EquationDialog = QtWidgets.QDialog()
    ui = Ui_EquationDialog()
    ui.setupUi(EquationDialog)
    EquationDialog.show()
    sys.exit(app.exec_())
