# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Desarrollo\ReDS\gui\launcher_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upperLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.upperLogoLabel.setText("")
        self.upperLogoLabel.setPixmap(QtGui.QPixmap(":/logos/logos/upper_logo.png"))
        self.upperLogoLabel.setObjectName("upperLogoLabel")
        self.verticalLayout.addWidget(self.upperLogoLabel)
        self.moduleHLayout = QtWidgets.QHBoxLayout()
        self.moduleHLayout.setObjectName("moduleHLayout")
        self.moduleAPushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moduleAPushButton.setFont(font)
        self.moduleAPushButton.setObjectName("moduleAPushButton")
        self.moduleHLayout.addWidget(self.moduleAPushButton)
        self.moduleBPushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moduleBPushButton.setFont(font)
        self.moduleBPushButton.setObjectName("moduleBPushButton")
        self.moduleHLayout.addWidget(self.moduleBPushButton)
        self.verticalLayout.addLayout(self.moduleHLayout)
        self.lowerLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.lowerLogoLabel.setText("")
        self.lowerLogoLabel.setPixmap(QtGui.QPixmap(":/logos/logos/lower_logo.png"))
        self.lowerLogoLabel.setObjectName("lowerLogoLabel")
        self.verticalLayout.addWidget(self.lowerLogoLabel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.moduleAPushButton.setText(_translate("MainWindow", "Modulo A: Reconstrucción de trazas"))
        self.moduleBPushButton.setText(_translate("MainWindow", "Modulo B: Reconstrucción de disparos"))
import assets_rc
