# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainB_window_v1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1261, 828)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.inputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.inputGroupBoxVLayout = QtWidgets.QVBoxLayout(self.inputGroupBox)
        self.inputGroupBoxVLayout.setObjectName("inputGroupBoxVLayout")
        self.dataTreeWidget = QtWidgets.QTreeWidget(self.inputGroupBox)
        self.dataTreeWidget.setObjectName("dataTreeWidget")
        self.inputGroupBoxVLayout.addWidget(self.dataTreeWidget)
        self.inputHLayout = QtWidgets.QHBoxLayout()
        self.inputHLayout.setObjectName("inputHLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.inputHLayout.addItem(spacerItem)
        self.typeDataLabel = QtWidgets.QLabel(self.inputGroupBox)
        self.typeDataLabel.setObjectName("typeDataLabel")
        self.inputHLayout.addWidget(self.typeDataLabel)
        self.dataComboBox = QtWidgets.QComboBox(self.inputGroupBox)
        self.dataComboBox.setObjectName("dataComboBox")
        self.dataComboBox.addItem("")
        self.dataComboBox.addItem("")
        self.inputHLayout.addWidget(self.dataComboBox)
        self.loadPushButton = QtWidgets.QPushButton(self.inputGroupBox)
        self.loadPushButton.setObjectName("loadPushButton")
        self.inputHLayout.addWidget(self.loadPushButton)
        self.clearDataPushButton = QtWidgets.QPushButton(self.inputGroupBox)
        self.clearDataPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearDataPushButton.setIcon(icon)
        self.clearDataPushButton.setObjectName("clearDataPushButton")
        self.inputHLayout.addWidget(self.clearDataPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.inputHLayout.addItem(spacerItem1)
        self.inputGroupBoxVLayout.addLayout(self.inputHLayout)
        self.mainLayout.addWidget(self.inputGroupBox)
        self.algorithmGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.algorithmGroupBox.setObjectName("algorithmGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.algorithmGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.algorithmComboBox = QtWidgets.QComboBox(self.algorithmGroupBox)
        self.algorithmComboBox.setObjectName("algorithmComboBox")
        self.algorithmComboBox.addItem("")
        self.horizontalLayout.addWidget(self.algorithmComboBox)
        self.algorithmPushButton = QtWidgets.QPushButton(self.algorithmGroupBox)
        self.algorithmPushButton.setEnabled(True)
        self.algorithmPushButton.setAutoFillBackground(False)
        self.algorithmPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.algorithmPushButton.setIcon(icon1)
        self.algorithmPushButton.setObjectName("algorithmPushButton")
        self.horizontalLayout.addWidget(self.algorithmPushButton)
        self.horizontalLayout.setStretch(0, 10)
        self.mainLayout.addWidget(self.algorithmGroupBox)
        self.samplingGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.samplingGroupBox.setObjectName("samplingGroupBox")
        self.samplingGroupBoxVLayout = QtWidgets.QVBoxLayout(self.samplingGroupBox)
        self.samplingGroupBoxVLayout.setObjectName("samplingGroupBoxVLayout")
        self.samplingHLayout = QtWidgets.QHBoxLayout()
        self.samplingHLayout.setObjectName("samplingHLayout")
        self.samplingTypeLabel = QtWidgets.QLabel(self.samplingGroupBox)
        self.samplingTypeLabel.setObjectName("samplingTypeLabel")
        self.samplingHLayout.addWidget(self.samplingTypeLabel)
        self.samplingTypeComboBox = QtWidgets.QComboBox(self.samplingGroupBox)
        self.samplingTypeComboBox.setObjectName("samplingTypeComboBox")
        self.samplingTypeComboBox.addItem("")
        self.samplingTypeComboBox.addItem("")
        self.samplingTypeComboBox.addItem("")
        self.samplingTypeComboBox.addItem("")
        self.samplingHLayout.addWidget(self.samplingTypeComboBox)
        self.compressLabel = QtWidgets.QLabel(self.samplingGroupBox)
        self.compressLabel.setObjectName("compressLabel")
        self.samplingHLayout.addWidget(self.compressLabel)
        self.compressSpinBox = QtWidgets.QSpinBox(self.samplingGroupBox)
        self.compressSpinBox.setPrefix("")
        self.compressSpinBox.setMinimum(1)
        self.compressSpinBox.setMaximum(99)
        self.compressSpinBox.setProperty("value", 50)
        self.compressSpinBox.setObjectName("compressSpinBox")
        self.samplingHLayout.addWidget(self.compressSpinBox)
        self.samplingHLayout.setStretch(1, 4)
        self.samplingHLayout.setStretch(3, 2)
        self.samplingGroupBoxVLayout.addLayout(self.samplingHLayout)
        self.samplingHLine = QtWidgets.QFrame(self.samplingGroupBox)
        self.samplingHLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.samplingHLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.samplingHLine.setObjectName("samplingHLine")
        self.samplingGroupBoxVLayout.addWidget(self.samplingHLine)
        self.elementHLayout = QtWidgets.QHBoxLayout()
        self.elementHLayout.setObjectName("elementHLayout")
        self.elementLabel = QtWidgets.QLabel(self.samplingGroupBox)
        self.elementLabel.setObjectName("elementLabel")
        self.elementHLayout.addWidget(self.elementLabel)
        self.elementLineEdit = QtWidgets.QLineEdit(self.samplingGroupBox)
        self.elementLineEdit.setObjectName("elementLineEdit")
        self.elementHLayout.addWidget(self.elementLineEdit)
        self.elementHelpButton = QtWidgets.QPushButton(self.samplingGroupBox)
        self.elementHelpButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.elementHelpButton.setIcon(icon2)
        self.elementHelpButton.setObjectName("elementHelpButton")
        self.elementHLayout.addWidget(self.elementHelpButton)
        self.samplingGroupBoxVLayout.addLayout(self.elementHLayout)
        self.jitterHLayout = QtWidgets.QHBoxLayout()
        self.jitterHLayout.setObjectName("jitterHLayout")
        self.gammaLabel = QtWidgets.QLabel(self.samplingGroupBox)
        self.gammaLabel.setText("")
        self.gammaLabel.setPixmap(QtGui.QPixmap(":/parameters/parameters/gamma.png"))
        self.gammaLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gammaLabel.setObjectName("gammaLabel")
        self.jitterHLayout.addWidget(self.gammaLabel)
        self.gammaSpinBox = QtWidgets.QSpinBox(self.samplingGroupBox)
        self.gammaSpinBox.setMinimum(1)
        self.gammaSpinBox.setMaximum(999)
        self.gammaSpinBox.setProperty("value", 2)
        self.gammaSpinBox.setObjectName("gammaSpinBox")
        self.jitterHLayout.addWidget(self.gammaSpinBox)
        self.epsilonLabel = QtWidgets.QLabel(self.samplingGroupBox)
        self.epsilonLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.epsilonLabel.setText("")
        self.epsilonLabel.setPixmap(QtGui.QPixmap(":/parameters/parameters/epsilon.png"))
        self.epsilonLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.epsilonLabel.setWordWrap(False)
        self.epsilonLabel.setObjectName("epsilonLabel")
        self.jitterHLayout.addWidget(self.epsilonLabel)
        self.epsilonSpinBox = QtWidgets.QSpinBox(self.samplingGroupBox)
        self.epsilonSpinBox.setMinimum(1)
        self.epsilonSpinBox.setMaximum(999)
        self.epsilonSpinBox.setSingleStep(2)
        self.epsilonSpinBox.setObjectName("epsilonSpinBox")
        self.jitterHLayout.addWidget(self.epsilonSpinBox)
        self.jitterPushButton = QtWidgets.QPushButton(self.samplingGroupBox)
        self.jitterPushButton.setText("")
        self.jitterPushButton.setIcon(icon1)
        self.jitterPushButton.setObjectName("jitterPushButton")
        self.jitterHLayout.addWidget(self.jitterPushButton)
        self.jitterHLayout.setStretch(0, 2)
        self.jitterHLayout.setStretch(1, 4)
        self.jitterHLayout.setStretch(2, 2)
        self.jitterHLayout.setStretch(3, 4)
        self.samplingGroupBoxVLayout.addLayout(self.jitterHLayout)
        self.sdHLayout = QtWidgets.QHBoxLayout()
        self.sdHLayout.setObjectName("sdHLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sdHLayout.addItem(spacerItem2)
        self.seedHLayout = QtWidgets.QHBoxLayout()
        self.seedHLayout.setObjectName("seedHLayout")
        self.seedCheckBox = QtWidgets.QCheckBox(self.samplingGroupBox)
        self.seedCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.seedCheckBox.setObjectName("seedCheckBox")
        self.seedHLayout.addWidget(self.seedCheckBox)
        self.seedLabel = QtWidgets.QLabel(self.samplingGroupBox)
        self.seedLabel.setObjectName("seedLabel")
        self.seedHLayout.addWidget(self.seedLabel)
        self.seedSpinBox = QtWidgets.QSpinBox(self.samplingGroupBox)
        self.seedSpinBox.setEnabled(False)
        self.seedSpinBox.setSuffix("")
        self.seedSpinBox.setPrefix("")
        self.seedSpinBox.setMinimum(-999)
        self.seedSpinBox.setMaximum(999)
        self.seedSpinBox.setObjectName("seedSpinBox")
        self.seedHLayout.addWidget(self.seedSpinBox)
        self.seedHelpButton = QtWidgets.QPushButton(self.samplingGroupBox)
        self.seedHelpButton.setText("")
        self.seedHelpButton.setIcon(icon2)
        self.seedHelpButton.setObjectName("seedHelpButton")
        self.seedHLayout.addWidget(self.seedHelpButton)
        self.sdHLayout.addLayout(self.seedHLayout)
        self.samplingGroupBoxVLayout.addLayout(self.sdHLayout)
        self.mainLayout.addWidget(self.samplingGroupBox)
        self.runGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.runGroupBox.setObjectName("runGroupBox")
        self.runGroupBoxVLayout = QtWidgets.QVBoxLayout(self.runGroupBox)
        self.runGroupBoxVLayout.setObjectName("runGroupBoxVLayout")
        self.saveAsHLayout = QtWidgets.QHBoxLayout()
        self.saveAsHLayout.setObjectName("saveAsHLayout")
        self.saveAsLabel = QtWidgets.QLabel(self.runGroupBox)
        self.saveAsLabel.setObjectName("saveAsLabel")
        self.saveAsHLayout.addWidget(self.saveAsLabel)
        self.saveAsLineEdit = QtWidgets.QLineEdit(self.runGroupBox)
        self.saveAsLineEdit.setObjectName("saveAsLineEdit")
        self.saveAsHLayout.addWidget(self.saveAsLineEdit)
        self.saveAsPushButton = QtWidgets.QPushButton(self.runGroupBox)
        self.saveAsPushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAsPushButton.setIcon(icon3)
        self.saveAsPushButton.setObjectName("saveAsPushButton")
        self.saveAsHLayout.addWidget(self.saveAsPushButton)
        self.runGroupBoxVLayout.addLayout(self.saveAsHLayout)
        self.startHLayout = QtWidgets.QHBoxLayout()
        self.startHLayout.setSpacing(6)
        self.startHLayout.setObjectName("startHLayout")
        self.experimentProgressBar = QtWidgets.QProgressBar(self.runGroupBox)
        self.experimentProgressBar.setProperty("value", 0)
        self.experimentProgressBar.setObjectName("experimentProgressBar")
        self.startHLayout.addWidget(self.experimentProgressBar)
        self.startPushButton = QtWidgets.QPushButton(self.runGroupBox)
        self.startPushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startPushButton.setIcon(icon4)
        self.startPushButton.setObjectName("startPushButton")
        self.startHLayout.addWidget(self.startPushButton)
        self.runGroupBoxVLayout.addLayout(self.startHLayout)
        self.mainLayout.addWidget(self.runGroupBox)
        self.resultGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.resultGroupBox.setObjectName("resultGroupBox")
        self.resultGroupBoxHLayout = QtWidgets.QVBoxLayout(self.resultGroupBox)
        self.resultGroupBoxHLayout.setObjectName("resultGroupBoxHLayout")
        self.resultHLayout = QtWidgets.QHBoxLayout()
        self.resultHLayout.setObjectName("resultHLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.resultHLayout.addItem(spacerItem3)
        self.resultLabel = QtWidgets.QLabel(self.resultGroupBox)
        self.resultLabel.setObjectName("resultLabel")
        self.resultHLayout.addWidget(self.resultLabel)
        self.resultPushButton = QtWidgets.QPushButton(self.resultGroupBox)
        self.resultPushButton.setAutoFillBackground(False)
        self.resultPushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resultPushButton.setIcon(icon5)
        self.resultPushButton.setAutoDefault(False)
        self.resultPushButton.setDefault(False)
        self.resultPushButton.setFlat(False)
        self.resultPushButton.setObjectName("resultPushButton")
        self.resultHLayout.addWidget(self.resultPushButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.resultHLayout.addItem(spacerItem4)
        self.resultHLayout.setStretch(0, 1)
        self.resultHLayout.setStretch(1, 1)
        self.resultHLayout.setStretch(2, 1)
        self.resultHLayout.setStretch(3, 1)
        self.resultGroupBoxHLayout.addLayout(self.resultHLayout)
        self.mainLayout.addWidget(self.resultGroupBox)
        self.horizontalLayout_2.addLayout(self.mainLayout)
        self.tuningTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tuningTabWidget.setObjectName("tuningTabWidget")
        self.expTuningReportTab1 = QtWidgets.QWidget()
        self.expTuningReportTab1.setObjectName("expTuningReportTab1")
        self.expTuningReportTab1VLayout = QtWidgets.QVBoxLayout(self.expTuningReportTab1)
        self.expTuningReportTab1VLayout.setObjectName("expTuningReportTab1VLayout")
        self.graphicTuningReportWidget = QtWidgets.QWidget(self.expTuningReportTab1)
        self.graphicTuningReportWidget.setObjectName("graphicTuningReportWidget")
        self.graphicTuningReportWidgetVLayout = QtWidgets.QVBoxLayout(self.graphicTuningReportWidget)
        self.graphicTuningReportWidgetVLayout.setContentsMargins(0, 0, 0, 0)
        self.graphicTuningReportWidgetVLayout.setSpacing(0)
        self.graphicTuningReportWidgetVLayout.setObjectName("graphicTuningReportWidgetVLayout")
        self.graphicTuningReportVLayout = QtWidgets.QVBoxLayout()
        self.graphicTuningReportVLayout.setObjectName("graphicTuningReportVLayout")
        self.graphicTuningReportWidgetVLayout.addLayout(self.graphicTuningReportVLayout)
        self.expTuningReportTab1VLayout.addWidget(self.graphicTuningReportWidget)
        self.tuningTabWidget.addTab(self.expTuningReportTab1, "")
        self.horizontalLayout_2.addWidget(self.tuningTabWidget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 10)
        mainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.aboutOfAction = QtWidgets.QAction(mainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutOfAction.setIcon(icon6)
        self.aboutOfAction.setObjectName("aboutOfAction")
        self.reportAction = QtWidgets.QAction(mainWindow)
        self.reportAction.setIcon(icon5)
        self.reportAction.setObjectName("reportAction")
        self.action = QtWidgets.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon7)
        self.action.setObjectName("action")
        self.tuningAction = QtWidgets.QAction(mainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/tuning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tuningAction.setIcon(icon8)
        self.tuningAction.setObjectName("tuningAction")
        self.comparisonAction = QtWidgets.QAction(mainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/comparison.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comparisonAction.setIcon(icon9)
        self.comparisonAction.setObjectName("comparisonAction")
        self.toolBar.addAction(self.aboutOfAction)

        self.retranslateUi(mainWindow)
        self.tuningTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "9836 Proyecto de Sísmica"))
        self.inputGroupBox.setTitle(_translate("mainWindow", "Datos sísmicos"))
        self.dataTreeWidget.headerItem().setText(0, _translate("mainWindow", "Datos actuales"))
        self.typeDataLabel.setText(_translate("mainWindow", "Tipo:"))
        self.dataComboBox.setItemText(0, _translate("mainWindow", "Datos completos"))
        self.dataComboBox.setItemText(1, _translate("mainWindow", "Datos incompletos"))
        self.loadPushButton.setText(_translate("mainWindow", "Cargar"))
        self.algorithmGroupBox.setTitle(_translate("mainWindow", "Algoritmos"))
        self.algorithmComboBox.setItemText(0, _translate("mainWindow", "Fast Marching"))
        self.algorithmPushButton.setToolTip(_translate("mainWindow", "Ver ecuación"))
        self.samplingGroupBox.setTitle(_translate("mainWindow", "Submuestreo"))
        self.samplingTypeLabel.setText(_translate("mainWindow", "Tipo"))
        self.samplingTypeComboBox.setItemText(0, _translate("mainWindow", "Aleatorio"))
        self.samplingTypeComboBox.setItemText(1, _translate("mainWindow", "Uniforme"))
        self.samplingTypeComboBox.setItemText(2, _translate("mainWindow", "Jitter"))
        self.samplingTypeComboBox.setItemText(3, _translate("mainWindow", "Lista"))
        self.compressLabel.setText(_translate("mainWindow", "Compresión"))
        self.compressSpinBox.setSuffix(_translate("mainWindow", "%"))
        self.elementLabel.setText(_translate("mainWindow", "Elementos"))
        self.seedCheckBox.setText(_translate("mainWindow", "Usar semilla"))
        self.seedLabel.setText(_translate("mainWindow", "Valor"))
        self.runGroupBox.setTitle(_translate("mainWindow", "Experimentos"))
        self.saveAsLabel.setText(_translate("mainWindow", "Guardar como"))
        self.resultGroupBox.setTitle(_translate("mainWindow", "Resultados"))
        self.resultLabel.setText(_translate("mainWindow", "Visualización"))
        self.tuningTabWidget.setTabText(self.tuningTabWidget.indexOf(self.expTuningReportTab1), _translate("mainWindow", "Experimento"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.aboutOfAction.setText(_translate("mainWindow", "about"))
        self.aboutOfAction.setToolTip(_translate("mainWindow", "<html><head/><body><p>Acerca de este proyecto</p></body></html>"))
        self.reportAction.setText(_translate("mainWindow", "report"))
        self.reportAction.setToolTip(_translate("mainWindow", "Visualización de resultados"))
        self.action.setText(_translate("mainWindow", "main"))
        self.action.setToolTip(_translate("mainWindow", "Ir al menú principal"))
        self.tuningAction.setText(_translate("mainWindow", "tuning"))
        self.tuningAction.setToolTip(_translate("mainWindow", "Ajuste de parámetros"))
        self.comparisonAction.setText(_translate("mainWindow", "comparison"))
        self.comparisonAction.setToolTip(_translate("mainWindow", "Hacer comparación de experimento con todos los algoritmos"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
